version: '3.8'

services:
  php:
    image: php:8.2-apache
    container_name: php
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DB: hellokant
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8081:8080"